In [417]:
import json
import pandas as pd
with open('py_challange_input.json') as f:
    data = json.load(f)

In [418]:
type(data)

dict

In [419]:
data

{'Cricket': [{'formats': [{'formatName': 'T20',
     'formatDayType': 'Half day match',
     'regions': [{'id': 666,
       'name': 'north',
       'isInternational': False,
       'matches': [{'id': 6038,
         'startTime': 1629944520,
         'team1': 'T1',
         'team2': 'T2',
         'venue': 'V1',
         'streaming': {'liveStream': {'provider': 'north-sky',
           'channel': '001'}},
         'results': {'winner': 'T2', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/north/t1vst2/v1/6038',
         'isInternational': False},
        {'id': 6039,
         'startTime': 1629944520,
         'team1': 'T2',
         'team2': 'T3',
         'venue': 'V2',
         'streaming': {'liveStream': {'provider': 'north-sky',
           'channel': '002'}},
         'results': {'winner': 'T2', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/north/t2vst3/v2/6039',
         'isInternational': False},
        {'id': 6040,
         'startTime': 1629944520,
         'team1': 'T3',
         'team2': 'T4',
         'venue': 'V3',
         'streaming': {'liveStream': {'provider': 'north-sky',
           'channel': '003'}},
         'results': {'winner': 'T4', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/north/t3vst4/v3/6040',
         'isInternational': False},
        {'id': 6041,
         'startTime': 1629944520,
         'team1': 'T4',
         'team2': 'T1',
         'venue': 'V4',
         'streaming': {'liveStream': {'provider': 'north-sky',
           'channel': '004'}},
         'results': {'winner': '', 'points': 0, 'resultsWithheld': True},
         'httpLink': 'cric/t20/north/t4vst1/v4/6041',
         'isInternational': False}]},
      {'id': 777,
       'name': 'south',
       'isInternational': False,
       'streamingAvailable': False,
       'matches': [{'id': 7038,
         'startTime': 1629944520,
         'team1': 'T5',
         'team2': 'T6',
         'venue': 'V5',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '101'}},
         'results': {'winner': 'T6', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/south/t5vst6/v5/7038',
         'isInternational': False},
        {'id': 7039,
         'startTime': 1629944520,
         'team1': 'T6',
         'team2': 'T7',
         'venue': 'V6',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '102'}},
         'results': {'winner': '', 'points': 0, 'resultsWithheld': True},
         'httpLink': 'cric/t20/south/t6vst7/v6/7039',
         'isInternational': False},
        {'id': 7040,
         'startTime': 1629944520,
         'team1': 'T7',
         'team2': 'T8',
         'venue': 'V7',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '103'}},
         'results': {'winner': 'T8', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/south/t7vst8/v7/7040',
         'isInternational': False},
        {'id': 7041,
         'startTime': 1629944520,
         'team1': 'T8',
         'team2': 'T5',
         'venue': 'V8',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '104'}},
         'results': {'winner': 'T8', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/south/t8vst5/v8/7041',
         'isInternational': False}]},
      {'id': 888,
       'name': 'central',
       'isInternational': False,
       'streamingAvailable': False,
       'matches': [{'id': 8038,
         'startTime': 1629944520,
         'team1': 'T10',
         'team2': 'T11',
         'venue': 'V10',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '201'}},
         'results': {'winner': 'T10', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/central/t10vst11/v10/8038',
         'isInternational': False},
        {'id': 8039,
         'startTime': 1629944520,
         'team1': 'T11',
         'team2': 'T12',
         'venue': 'V11',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '202'}},
         'results': {'winner': 'T12', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/central/t11vst12/v11/8039',
         'isInternational': False},
        {'id': 8040,
         'startTime': 1629944520,
         'team1': 'T12',
         'team2': 'T13',
         'venue': 'V12',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '203'}},
         'results': {'winner': 'T12', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/central/t12vst13/v12/8040',
         'isInternational': False},
        {'id': 8041,
         'startTime': 1629944520,
         'team1': 'T13',
         'team2': 'T10',
         'venue': 'V13',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '204'}},
         'results': {'winner': 'T10', 'points': 2, 'resultsWithheld': False},
         'httpLink': 'cric/t20/central/t13vst10/v13/8041',
         'isInternational': False}]}]},
    {'formatName': 'ODI',
     'formatDayType': 'One day match',
     'regions': [{'id': 999,
       'name': 'NewZealand',
       'isInternational': True,
       'matches': [{'id': 16038,
         'startTime': 1629944520,
         'team1': 'T1',
         'team2': 'T2',
         'venue': 'NZ-V1',
         'streaming': {'liveStream': {'provider': 'nz-ez', 'channel': '001'}},
         'results': {'winner': 'T2', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/odi/nz/t1vst2/v1/16038',
         'isInternational': True},
        {'id': 16039,
         'startTime': 1629944520,
         'team1': 'T2',
         'team2': 'T3',
         'venue': 'NZ-V2',
         'streaming': {'liveStream': {'provider': 'nz-ez', 'channel': '002'}},
         'results': {'winner': 'T2', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/odi/nz/t2vst3/v2/16039',
         'isInternational': True},
        {'id': 16040,
         'startTime': 1629944520,
         'team1': 'T3',
         'team2': 'T4',
         'venue': 'NZ-V3',
         'streaming': {'liveStream': {'provider': 'nz-ez', 'channel': '003'}},
         'results': {'winner': 'T4', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/odi/nz/t3vst4/v3/16040',
         'isInternational': True},
        {'id': 16041,
         'startTime': 1629944520,
         'team1': 'T4',
         'team2': 'T1',
         'venue': 'NZ-V4',
         'streaming': {'liveStream': {'provider': 'nz-ez', 'channel': '004'}},
         'results': {'winner': 'T1', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/odi/nz/t4vst1/v4/16041',
         'isInternational': True}]},
      {'id': 777,
       'name': 'south',
       'isInternational': False,
       'streamingAvailable': False,
       'matches': [{'id': 17038,
         'startTime': 1629944520,
         'team1': 'T5',
         'team2': 'T6',
         'venue': 'V5',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '101'}},
         'results': {'winner': 'T5', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/t20/south/t5vst6/v5/17038',
         'isInternational': False},
        {'id': 17039,
         'startTime': 1629944520,
         'team1': 'T6',
         'team2': 'T7',
         'venue': 'V6',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '102'}},
         'results': {'winner': 'T6', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/t20/south/t6vst7/v6/17039',
         'isInternational': False},
        {'id': 17040,
         'startTime': 1629944520,
         'team1': 'T7',
         'team2': 'T8',
         'venue': 'V7',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '103'}},
         'results': {'winner': '', 'points': 0, 'resultsWithheld': True},
         'httpLink': 'cric/t20/south/t7vst8/v7/17040',
         'isInternational': False},
        {'id': 17041,
         'startTime': 1629944520,
         'team1': 'T8',
         'team2': 'T5',
         'venue': 'V8',
         'streaming': {'liveStream': {'provider': 'south-sky',
           'channel': '104'}},
         'results': {'winner': 'T8', 'points': 4, 'resultsWithheld': False},
         'httpLink': 'cric/t20/south/t8vst5/v8/17041',
         'isInternational': False}]},
      {'id': 888,
       'name': 'central',
       'isInternational': False,
       'matches': [{'id': 18038,
         'startTime': 1629944520,
         'team1': 'T10',
         'team2': 'T11',
         'venue': 'V10',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '201'}},
         'results': {'winner': 'T10', 'points': 4, 'resultsWithheld': False},
         'streamingAvailable': False,
         'availableStreamingType': None,
         'httpLink': 'cric/t20/central/t10vst11/v10/18038',
         'isInternational': False},
        {'id': 18039,
         'startTime': 1629944520,
         'team1': 'T11',
         'team2': 'T12',
         'venue': 'V11',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '202'}},
         'results': {'winner': 'T12', 'points': 4, 'resultsWithheld': False},
         'streamingAvailable': False,
         'availableStreamingType': None,
         'httpLink': 'cric/t20/central/t11vst12/v11/18039',
         'isInternational': False},
        {'id': 18040,
         'startTime': 1629944520,
         'team1': 'T12',
         'team2': 'T13',
         'venue': 'V12',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '203'}},
         'results': {'winner': 'T12', 'points': 4, 'resultsWithheld': False},
         'streamingAvailable': False,
         'availableStreamingType': None,
         'httpLink': 'cric/t20/central/t12vst13/v12/18040',
         'isInternational': False},
        {'id': 18041,
         'startTime': 1629944520,
         'team1': 'T13',
         'team2': 'T10',
         'venue': 'V13',
         'streaming': {'liveStream': {'provider': 'central-sky',
           'channel': '204'}},
         'results': {'winner': 'T10', 'points': 4, 'resultsWithheld': False},
         'streamingAvailable': False,
         'availableStreamingType': None,
         'httpLink': 'cric/t20/central/t13vst10/v13/18041',
         'isInternational': False}]}]}]}]}

In [420]:
aa = data['Cricket']
aa = aa[0]
aa = aa['formats']

In [421]:
team_1 = []
team_2 = []
id_1 = []
provider = []
winner = []
link = []
region = []
start_time = []
international = []
draw = []
points = []

In [422]:
## all  except name
#id, provider, winner, httplink, team1, team2, starttime
def get_info():
    for question in aa:
        list_1 = question['regions']
        for val in list_1:           
            list_2 = val['matches']
            for val_1 in list_2:
                team_1.append(val_1['team1'])
                team_2.append(val_1['team2'])
                id_1.append(val_1['id'])
                provider.append(val_1['streaming']['liveStream']['provider'])
                winner.append(val_1['results']['winner'])
                points.append(val_1['results']['points'])

                international.append(val_1['isInternational'])
                draw.append(val_1['results']['resultsWithheld'])
                link.append(val_1['httpLink'])
                start_time.append(val_1['startTime'])

In [423]:
get_info()

In [424]:
id_1

[6038,
 6039,
 6040,
 6041,
 7038,
 7039,
 7040,
 7041,
 8038,
 8039,
 8040,
 8041,
 16038,
 16039,
 16040,
 16041,
 17038,
 17039,
 17040,
 17041,
 18038,
 18039,
 18040,
 18041]

In [425]:
provider

['north-sky',
 'north-sky',
 'north-sky',
 'north-sky',
 'south-sky',
 'south-sky',
 'south-sky',
 'south-sky',
 'central-sky',
 'central-sky',
 'central-sky',
 'central-sky',
 'nz-ez',
 'nz-ez',
 'nz-ez',
 'nz-ez',
 'south-sky',
 'south-sky',
 'south-sky',
 'south-sky',
 'central-sky',
 'central-sky',
 'central-sky',
 'central-sky']

In [426]:
winner

['T2',
 'T2',
 'T4',
 '',
 'T6',
 '',
 'T8',
 'T8',
 'T10',
 'T12',
 'T12',
 'T10',
 'T2',
 'T2',
 'T4',
 'T1',
 'T5',
 'T6',
 '',
 'T8',
 'T10',
 'T12',
 'T12',
 'T10']

In [427]:
link

['cric/t20/north/t1vst2/v1/6038',
 'cric/t20/north/t2vst3/v2/6039',
 'cric/t20/north/t3vst4/v3/6040',
 'cric/t20/north/t4vst1/v4/6041',
 'cric/t20/south/t5vst6/v5/7038',
 'cric/t20/south/t6vst7/v6/7039',
 'cric/t20/south/t7vst8/v7/7040',
 'cric/t20/south/t8vst5/v8/7041',
 'cric/t20/central/t10vst11/v10/8038',
 'cric/t20/central/t11vst12/v11/8039',
 'cric/t20/central/t12vst13/v12/8040',
 'cric/t20/central/t13vst10/v13/8041',
 'cric/odi/nz/t1vst2/v1/16038',
 'cric/odi/nz/t2vst3/v2/16039',
 'cric/odi/nz/t3vst4/v3/16040',
 'cric/odi/nz/t4vst1/v4/16041',
 'cric/t20/south/t5vst6/v5/17038',
 'cric/t20/south/t6vst7/v6/17039',
 'cric/t20/south/t7vst8/v7/17040',
 'cric/t20/south/t8vst5/v8/17041',
 'cric/t20/central/t10vst11/v10/18038',
 'cric/t20/central/t11vst12/v11/18039',
 'cric/t20/central/t12vst13/v12/18040',
 'cric/t20/central/t13vst10/v13/18041']

In [428]:
team_1

['T1',
 'T2',
 'T3',
 'T4',
 'T5',
 'T6',
 'T7',
 'T8',
 'T10',
 'T11',
 'T12',
 'T13',
 'T1',
 'T2',
 'T3',
 'T4',
 'T5',
 'T6',
 'T7',
 'T8',
 'T10',
 'T11',
 'T12',
 'T13']

In [429]:
team_2

['T2',
 'T3',
 'T4',
 'T1',
 'T6',
 'T7',
 'T8',
 'T5',
 'T11',
 'T12',
 'T13',
 'T10',
 'T2',
 'T3',
 'T4',
 'T1',
 'T6',
 'T7',
 'T8',
 'T5',
 'T11',
 'T12',
 'T13',
 'T10']

In [430]:
start_time

[1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520,
 1629944520]

In [431]:
# for extracting region
region = []
def region_info():
    for question in aa:
        for l in question['regions']:
            for i in range(len(l['matches'])):
                region.append(l['name'])
    return region

In [432]:
region_info()

['north',
 'north',
 'north',
 'north',
 'south',
 'south',
 'south',
 'south',
 'central',
 'central',
 'central',
 'central',
 'NewZealand',
 'NewZealand',
 'NewZealand',
 'NewZealand',
 'south',
 'south',
 'south',
 'south',
 'central',
 'central',
 'central',
 'central']

In [433]:
list_11 = ['match_id', 'livestream_provider', 'winner_of_the_match', 
           'match_link','region_name', 'team1', 'team2', 'start_time']

In [434]:
ok = [dict(zip(['match_id'], [id_1[i]])) for i in range(len(id_1))]
ok

[{'match_id': 6038},
 {'match_id': 6039},
 {'match_id': 6040},
 {'match_id': 6041},
 {'match_id': 7038},
 {'match_id': 7039},
 {'match_id': 7040},
 {'match_id': 7041},
 {'match_id': 8038},
 {'match_id': 8039},
 {'match_id': 8040},
 {'match_id': 8041},
 {'match_id': 16038},
 {'match_id': 16039},
 {'match_id': 16040},
 {'match_id': 16041},
 {'match_id': 17038},
 {'match_id': 17039},
 {'match_id': 17040},
 {'match_id': 17041},
 {'match_id': 18038},
 {'match_id': 18039},
 {'match_id': 18040},
 {'match_id': 18041}]

In [435]:
j = 0
for element in ok:
    element['livestream_provider'] = provider[j]
    element['winner_of_the_match'] = winner[j]
    element['match_link'] = link[j]
    element['region_name'] = region[j]
    element['team1'] = team_1[j]
    element['team2'] = team_2[j]
    element['start_time'] = start_time[j]
    j+=1

In [436]:
ok

[{'match_id': 6038,
  'livestream_provider': 'north-sky',
  'winner_of_the_match': 'T2',
  'match_link': 'cric/t20/north/t1vst2/v1/6038',
  'region_name': 'north',
  'team1': 'T1',
  'team2': 'T2',
  'start_time': 1629944520},
 {'match_id': 6039,
  'livestream_provider': 'north-sky',
  'winner_of_the_match': 'T2',
  'match_link': 'cric/t20/north/t2vst3/v2/6039',
  'region_name': 'north',
  'team1': 'T2',
  'team2': 'T3',
  'start_time': 1629944520},
 {'match_id': 6040,
  'livestream_provider': 'north-sky',
  'winner_of_the_match': 'T4',
  'match_link': 'cric/t20/north/t3vst4/v3/6040',
  'region_name': 'north',
  'team1': 'T3',
  'team2': 'T4',
  'start_time': 1629944520},
 {'match_id': 6041,
  'livestream_provider': 'north-sky',
  'winner_of_the_match': '',
  'match_link': 'cric/t20/north/t4vst1/v4/6041',
  'region_name': 'north',
  'team1': 'T4',
  'team2': 'T1',
  'start_time': 1629944520},
 {'match_id': 7038,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': 'T6',
  'match_link': 'cric/t20/south/t5vst6/v5/7038',
  'region_name': 'south',
  'team1': 'T5',
  'team2': 'T6',
  'start_time': 1629944520},
 {'match_id': 7039,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': '',
  'match_link': 'cric/t20/south/t6vst7/v6/7039',
  'region_name': 'south',
  'team1': 'T6',
  'team2': 'T7',
  'start_time': 1629944520},
 {'match_id': 7040,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': 'T8',
  'match_link': 'cric/t20/south/t7vst8/v7/7040',
  'region_name': 'south',
  'team1': 'T7',
  'team2': 'T8',
  'start_time': 1629944520},
 {'match_id': 7041,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': 'T8',
  'match_link': 'cric/t20/south/t8vst5/v8/7041',
  'region_name': 'south',
  'team1': 'T8',
  'team2': 'T5',
  'start_time': 1629944520},
 {'match_id': 8038,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T10',
  'match_link': 'cric/t20/central/t10vst11/v10/8038',
  'region_name': 'central',
  'team1': 'T10',
  'team2': 'T11',
  'start_time': 1629944520},
 {'match_id': 8039,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T12',
  'match_link': 'cric/t20/central/t11vst12/v11/8039',
  'region_name': 'central',
  'team1': 'T11',
  'team2': 'T12',
  'start_time': 1629944520},
 {'match_id': 8040,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T12',
  'match_link': 'cric/t20/central/t12vst13/v12/8040',
  'region_name': 'central',
  'team1': 'T12',
  'team2': 'T13',
  'start_time': 1629944520},
 {'match_id': 8041,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T10',
  'match_link': 'cric/t20/central/t13vst10/v13/8041',
  'region_name': 'central',
  'team1': 'T13',
  'team2': 'T10',
  'start_time': 1629944520},
 {'match_id': 16038,
  'livestream_provider': 'nz-ez',
  'winner_of_the_match': 'T2',
  'match_link': 'cric/odi/nz/t1vst2/v1/16038',
  'region_name': 'NewZealand',
  'team1': 'T1',
  'team2': 'T2',
  'start_time': 1629944520},
 {'match_id': 16039,
  'livestream_provider': 'nz-ez',
  'winner_of_the_match': 'T2',
  'match_link': 'cric/odi/nz/t2vst3/v2/16039',
  'region_name': 'NewZealand',
  'team1': 'T2',
  'team2': 'T3',
  'start_time': 1629944520},
 {'match_id': 16040,
  'livestream_provider': 'nz-ez',
  'winner_of_the_match': 'T4',
  'match_link': 'cric/odi/nz/t3vst4/v3/16040',
  'region_name': 'NewZealand',
  'team1': 'T3',
  'team2': 'T4',
  'start_time': 1629944520},
 {'match_id': 16041,
  'livestream_provider': 'nz-ez',
  'winner_of_the_match': 'T1',
  'match_link': 'cric/odi/nz/t4vst1/v4/16041',
  'region_name': 'NewZealand',
  'team1': 'T4',
  'team2': 'T1',
  'start_time': 1629944520},
 {'match_id': 17038,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': 'T5',
  'match_link': 'cric/t20/south/t5vst6/v5/17038',
  'region_name': 'south',
  'team1': 'T5',
  'team2': 'T6',
  'start_time': 1629944520},
 {'match_id': 17039,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': 'T6',
  'match_link': 'cric/t20/south/t6vst7/v6/17039',
  'region_name': 'south',
  'team1': 'T6',
  'team2': 'T7',
  'start_time': 1629944520},
 {'match_id': 17040,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': '',
  'match_link': 'cric/t20/south/t7vst8/v7/17040',
  'region_name': 'south',
  'team1': 'T7',
  'team2': 'T8',
  'start_time': 1629944520},
 {'match_id': 17041,
  'livestream_provider': 'south-sky',
  'winner_of_the_match': 'T8',
  'match_link': 'cric/t20/south/t8vst5/v8/17041',
  'region_name': 'south',
  'team1': 'T8',
  'team2': 'T5',
  'start_time': 1629944520},
 {'match_id': 18038,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T10',
  'match_link': 'cric/t20/central/t10vst11/v10/18038',
  'region_name': 'central',
  'team1': 'T10',
  'team2': 'T11',
  'start_time': 1629944520},
 {'match_id': 18039,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T12',
  'match_link': 'cric/t20/central/t11vst12/v11/18039',
  'region_name': 'central',
  'team1': 'T11',
  'team2': 'T12',
  'start_time': 1629944520},
 {'match_id': 18040,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T12',
  'match_link': 'cric/t20/central/t12vst13/v12/18040',
  'region_name': 'central',
  'team1': 'T12',
  'team2': 'T13',
  'start_time': 1629944520},
 {'match_id': 18041,
  'livestream_provider': 'central-sky',
  'winner_of_the_match': 'T10',
  'match_link': 'cric/t20/central/t13vst10/v13/18041',
  'region_name': 'central',
  'team1': 'T13',
  'team2': 'T10',
  'start_time': 1629944520}]

In [445]:
with open('file_data.json', 'w') as file:
    json.dump(ok,file)

## DataFrame

In [437]:
final = {'match_id': id_1, 'livestream_provider': provider,
         'winner_of_the_match': winner,
        'match_link': link, 'region_name': region,'team1': team_1,
         'team2' : team_2, 'start_time':start_time,
        'international': international, 'draw': draw,
        'points': points}

In [438]:
df= pd.DataFrame(final)
df

,match_id,livestream_provider,winner_of_the_match,match_link,region_name,team1,team2,start_time,international,draw,points
0,6038,north-sky,T2,cric/t20/north/t1vst2/v1/6038,north,T1,T2,1629944520,False,False,2
1,6039,north-sky,T2,cric/t20/north/t2vst3/v2/6039,north,T2,T3,1629944520,False,False,2
2,6040,north-sky,T4,cric/t20/north/t3vst4/v3/6040,north,T3,T4,1629944520,False,False,2
3,6041,north-sky,,cric/t20/north/t4vst1/v4/6041,north,T4,T1,1629944520,False,True,0
4,7038,south-sky,T6,cric/t20/south/t5vst6/v5/7038,south,T5,T6,1629944520,False,False,2
5,7039,south-sky,,cric/t20/south/t6vst7/v6/7039,south,T6,T7,1629944520,False,True,0
6,7040,south-sky,T8,cric/t20/south/t7vst8/v7/7040,south,T7,T8,1629944520,False,False,2
7,7041,south-sky,T8,cric/t20/south/t8vst5/v8/7041,south,T8,T5,1629944520,False,False,2
8,8038,central-sky,T10,cric/t20/central/t10vst11/v10/8038,central,T10,T11,1629944520,False,False,2
9,8039,central-sky,T12,cric/t20/central/t11vst12/v11/8039,central,T11,T12,1629944520,False,False,2
10,8040,central-sky,T12,cric/t20/central/t12vst13/v12/8040,central,T12,T13,1629944520,False,False,2
11,8041,central-sky,T10,cric/t20/central/t13vst10/v13/8041,central,T13,T10,1629944520,False,False,2
12,16038,nz-ez,T2,cric/odi/nz/t1vst2/v1/16038,NewZealand,T1,T2,1629944520,True,False,4
13,16039,nz-ez,T2,cric/odi/nz/t2vst3/v2/16039,NewZealand,T2,T3,1629944520,True,False,4
14,16040,nz-ez,T4,cric/odi/nz/t3vst4/v3/16040,NewZealand,T3,T4,1629944520,True,False,4
15,16041,nz-ez,T1,cric/odi/nz/t4vst1/v4/16041,NewZealand,T4,T1,1629944520,True,False,4
16,17038,south-sky,T5,cric/t20/south/t5vst6/v5/17038,south,T5,T6,1629944520,False,False,4
17,17039,south-sky,T6,cric/t20/south/t6vst7/v6/17039,south,T6,T7,1629944520,False,False,4
18,17040,south-sky,,cric/t20/south/t7vst8/v7/17040,south,T7,T8,1629944520,False,True,0
19,17041,south-sky,T8,cric/t20/south/t8vst5/v8/17041,south,T8,T5,1629944520,False,False,4
20,18038,central-sky,T10,cric/t20/central/t10vst11/v10/18038,central,T10,T11,1629944520,False,False,4
21,18039,central-sky,T12,cric/t20/central/t11vst12/v11/18039,central,T11,T12,1629944520,False,False,4
22,18040,central-sky,T12,cric/t20/central/t12vst13/v12/18040,central,T12,T13,1629944520,False,False,4
23,18041,central-sky,T10,cric/t20/central/t13vst10/v13/18041,central,T13,T10,1629944520,False,False,4

In [439]:
df['region_name'].value_counts()

south         8
central       8
north         4
NewZealand    4
Name: region_name, dtype: int64

In [440]:
### 4 international matches 
# ALTERNATIVELY,
df['international'].value_counts()

False    20
True      4
Name: international, dtype: int64

### 4 matches held outside.

In [441]:
df.groupby('winner_of_the_match')['points'].count()

winner_of_the_match
       3
T1     1
T10    4
T12    4
T2     4
T4     2
T5     1
T6     2
T8     3
Name: points, dtype: int64

### T10, T12 and T2 scored highest points

In [442]:
df['region_name'].value_counts()/df.shape[0]*100

south         33.333333
central       33.333333
north         16.666667
NewZealand    16.666667
Name: region_name, dtype: float64

In [443]:
df['draw'].value_counts()

False    21
True      3
Name: draw, dtype: int64

In [444]:
df[df['draw'] == True][['match_id','team1','team2']]

    match_id team1 team2
3       6041    T4    T1
5       7039    T6    T7
18     17040    T7    T8